#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
# exec python manage.py runserver_plus 0.0.0.0:8000
exec python manage.py runserver 0.0.0.0:8000

# TODO: https://github.com/pallets/werkzeug/issues/2603 - check if Werkzeug is availiable with version 2.3 and update local requirements and check if server still restarts with every request.
