# Generated by Django 4.0.8 on 2023-01-11 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='discord',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporation',
            name='ws_wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('59218adc-33ec-4d50-b565-92288f8e6aea'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
