# Generated by Django 4.0.8 on 2023-01-11 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0002_corporation_discord_corporation_ws_wins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4430d56a-f4f1-47ab-9055-4004464fba54'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
