# Generated by Django 4.0.8 on 2023-01-11 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0003_alter_corporation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d19b8239-69a3-4336-acb2-10202aec17d2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
