# Generated by Django 4.0.8 on 2023-01-11 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0005_alter_corporation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('38781079-cdf5-44f9-b012-4862870388a1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
