# Generated by Django 4.0.8 on 2023-01-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0007_alter_corporation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
