# Generated by Django 4.0.8 on 2023-01-12 07:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0008_alter_corporation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7dbcee3f-73c9-44a4-ba7d-df8c8ef16d7b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
