# Generated by Django 4.1.5 on 2023-01-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporations", "0010_alter_corporation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporation",
            name="secret",
            field=models.CharField(default="secret", max_length=20),
        ),
    ]
