# Generated by Django 4.1.5 on 2023-02-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporations", "0011_corporation_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corporation",
            name="secret",
            field=models.CharField(max_length=20),
        ),
    ]
