# Generated by Django 4.1.5 on 2023-04-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporations", "0013_filter"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporation",
            name="server_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
