# Generated by Django 4.1.5 on 2023-04-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporations", "0015_alter_corporation_server_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corporation",
            name="server_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="corporation",
            constraint=models.CheckConstraint(
                check=models.Q(("server_id__gte", 0)),
                name="corporation_server_id__gte_0",
                violation_error_message="Server ID must be positive integer number",
            ),
        ),
    ]
