# Generated by Django 4.1.5 on 2023-04-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporations", "0016_alter_corporation_server_id_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="corporation",
            name="corporation_server_id__gte_0",
        ),
        migrations.RemoveField(
            model_name="corporation",
            name="server_id",
        ),
        migrations.AddField(
            model_name="corporation",
            name="role_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name="corporation",
            constraint=models.CheckConstraint(
                check=models.Q(("role_id__gte", 0)),
                name="corporation_role_id__gte_0",
                violation_error_message="Role ID must be positive integer number",
            ),
        ),
    ]
