# Generated by Django 4.0.8 on 2023-01-11 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0004_alter_corporation_id'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='corporation',
            field=models.ManyToManyField(blank=True, related_name='corporation_members', to='corporations.corporation'),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d19b8239-69a3-4336-acb2-10202aec17d2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
