# Generated by Django 4.1.5 on 2023-01-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_alter_mining_position_alter_shield_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mining",
            name="position",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="shield",
            name="position",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="support",
            name="position",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="trade",
            name="position",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="position",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
