# Generated by Django 4.0.8 on 2023-01-11 15:03

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_corporation_alter_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='preferences',
        ),
        migrations.AddField(
            model_name='member',
            name='ws_ship_roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('A', 'All roles'), ('H', 'Hunter'), ('U', 'Utility'), ('D', 'Defensive'), ('V', 'Offensive Vanguard'), ('P', 'Offensive Phalanx')], max_length=1), blank=True, null=True, size=6),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.UUIDField(default=uuid.UUID('261d4e5c-4505-4d3f-a1ea-90bd7b9ccd04'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
