# Generated by Django 4.1.5 on 2023-01-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_alter_mining_position_alter_shield_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weapon",
            name="name",
            field=models.CharField(
                choices=[
                    ("BATTERY", "Battery"),
                    ("LASER", "Laser"),
                    ("MASS_BATTERY", "Mass Battery"),
                    ("DUAL_LASER", "Dual Laser"),
                    ("BARRAGE", "Barrage"),
                    ("DART_LAUNCHER", "Dart Launcher"),
                ],
                default="BATTERY",
                max_length=30,
            ),
        ),
    ]
