# Generated by Django 4.1.5 on 2023-03-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "members",
            "0006_alter_mining_max_alter_shield_max_alter_support_max_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mining",
            name="members_mining_max_value__lte_12",
        ),
        migrations.RemoveConstraint(
            model_name="shield",
            name="members_shield_max_value__lte_12",
        ),
        migrations.RemoveConstraint(
            model_name="support",
            name="members_support_max_value__lte_12",
        ),
        migrations.RemoveConstraint(
            model_name="support",
            name="members_support_max_value__gt_1_or_lt_12",
        ),
        migrations.RemoveConstraint(
            model_name="trade",
            name="members_trade_max_value__lte_12",
        ),
        migrations.RemoveConstraint(
            model_name="weapon",
            name="members_weapon_max_value__lte_12",
        ),
        migrations.RenameField(
            model_name="mining",
            old_name="value",
            new_name="set",
        ),
        migrations.RenameField(
            model_name="shield",
            old_name="value",
            new_name="set",
        ),
        migrations.RenameField(
            model_name="support",
            old_name="value",
            new_name="set",
        ),
        migrations.RenameField(
            model_name="trade",
            old_name="value",
            new_name="set",
        ),
        migrations.RenameField(
            model_name="weapon",
            old_name="value",
            new_name="set",
        ),
        migrations.AddConstraint(
            model_name="mining",
            constraint=models.CheckConstraint(
                check=models.Q(("set__lte", 12)),
                name="members_mining_max_set__lte_12",
                violation_error_message="Maximum value you can set must be lower than 12",
            ),
        ),
        migrations.AddConstraint(
            model_name="shield",
            constraint=models.CheckConstraint(
                check=models.Q(("set__lte", 12)),
                name="members_shield_max_set__lte_12",
                violation_error_message="Maximum value you can set must be lower than 12",
            ),
        ),
        migrations.AddConstraint(
            model_name="support",
            constraint=models.CheckConstraint(
                check=models.Q(("set__lte", 12)),
                name="members_support_max_set__lte_12",
                violation_error_message="Maximum value you can set must be lower than 12",
            ),
        ),
        migrations.AddConstraint(
            model_name="support",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("name", "SANCTUARY"), ("set__lte", 1)),
                    models.Q(
                        (
                            "name__in",
                            [
                                "EMP",
                                "TELEPORT",
                                "RED_STAR_LIFE_EXTENDER",
                                "REMOTE_REPAIR",
                                "TIME_WRAP",
                                "UNITY",
                                "STEALTH",
                                "FORTIFY",
                                "IMPULSE",
                                "ALPHA_ROCKET",
                                "SALVAGE",
                                "SUPRESS",
                                "DESTINY",
                                "BARRIER",
                                "VENEGANCE",
                                "DELTA_ROCKET",
                                "LEAP",
                                "BOND",
                                "LASER_TURRET",
                                "ALPHA_DRONE",
                                "SUSPEND",
                                "OMEGA_ROCKET",
                                "REMOTE_BOMB",
                            ],
                        ),
                        ("set__lte", 12),
                    ),
                    _connector="OR",
                ),
                name="members_support_max_set__gt_1_or_lt_12",
                violation_error_message="For Sanctuary maximum value you can set must be lower than 1, rest attributes must be lower than 12",
            ),
        ),
        migrations.AddConstraint(
            model_name="trade",
            constraint=models.CheckConstraint(
                check=models.Q(("set__lte", 12)),
                name="members_trade_max_set__lte_12",
                violation_error_message="Maximum value you can set must be lower than 12",
            ),
        ),
        migrations.AddConstraint(
            model_name="weapon",
            constraint=models.CheckConstraint(
                check=models.Q(("set__lte", 12)),
                name="members_weapon_max_set__lte_12",
                violation_error_message="Maximum value you can set must be lower than 12",
            ),
        ),
    ]
