# Generated by Django 4.1.5 on 2023-04-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_remove_mining_members_mining_max_value__lte_12_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="hsc_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.CheckConstraint(
                check=models.Q(("hsc_id__gte", 0)),
                name="member_hsc_id__gte_0",
                violation_error_message="HSC ID must be positive integer number",
            ),
        ),
    ]
