# Generated by Django 4.1.5 on 2023-04-15 19:50

from django.db import migrations, models
import django.db.models.deletion


def assign_corporation_id(apps, schema_editor):

    Member = apps.get_model("members", "Member")
    for member in Member.objects.all():
        corporation = member.corporation.all().first()
        member.corporation_id = corporation
        member.save()

class Migration(migrations.Migration):

    dependencies = [
        (
            "corporations",
            "0017_remove_corporation_corporation_server_id__gte_0_and_more",
        ),
        ("members", "0008_member_hsc_id_member_member_hsc_id__gte_0"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="corporation_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_corporation",
                to="corporations.corporation",
            ),
        ),
        migrations.RunPython(assign_corporation_id),
    ]
