# Generated by Django 4.1.5 on 2023-04-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_member_corporation_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="corporation",
        ),
    ]
