# Generated by Django 4.1.5 on 2023-04-15 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "corporations",
            "0017_remove_corporation_corporation_server_id__gte_0_and_more",
        ),
        ("members", "0011_remove_member_corporation_id_member_corporation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="corporation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="corporation_members",
                to="corporations.corporation",
            ),
        ),
    ]
