# Generated by Django 4.1.5 on 2023-04-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0012_alter_member_corporation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="max_mods",
            new_name="miner_level",
        ),
        migrations.AddField(
            model_name="member",
            name="transport_level",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
