# Generated by Django 4.1.5 on 2023-05-13 20:12

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "corporations",
            "0017_remove_corporation_corporation_server_id__gte_0_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WsLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opponent_corporation_name",
                    models.CharField(blank=True, max_length=90),
                ),
                (
                    "match_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("5vs5", "5 vs. 5"),
                            ("10vs10", "10 vs. 10"),
                            ("15vs15", "15 vs. 15"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("match_start", models.DateTimeField(blank=True, null=True)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corporation_wslogs",
                        to="corporations.corporation",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
